# Generated by Django 3.2.1 on 2024-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Bloodbank-picture', verbose_name='Image'),
        ),
    ]
